name: RainB0
version: '${project.version}'
main: com.black.minecraft.b0rain.B0rain
api-version: '1.18'
authors: [ b0b0b0 ]
website: https://black-minecraft.com/
description: Realistic weather effects - slowness in rain, elytra restrictions, and more!

commands:
  rainb0:
    description: Main command for RainB0 plugin
    usage: /<command> <reload|status|toggle|info>
    aliases: [rb0, rain]

permissions:
  rainb0.reload:
    description: Allows reloading RainB0 configuration
    default: op
  rainb0.bypass:
    description: Bypass all rain slowness effects
    default: false
  rainb0.elytra.bypass:
    description: Bypass elytra flight restrictions in rain
    default: false
  rainb0.status:
    description: View plugin status
    default: op
  rainb0.toggle:
    description: Toggle rain effect for yourself
    default: true
  rainb0.toggle.others:
    description: Toggle rain effect for other players
    default: op
