name: WeatherFX
version: '${project.version}'
main: com.black.minecraft.b0rain.B0rain
api-version: '1.18'
authors: [ IkdanYT ]
website: https://github.com/IkdanYT/WeatherFX
description: Realistic weather effects - slowness in rain, elytra restrictions, ambient sounds and more!

commands:
  wfx:
    description: Main command for WeatherFX plugin
    usage: /<command> <reload|status|toggle|info>
    aliases: [weatherfx, rain]

permissions:
  wfx.reload:
    description: Allows reloading WeatherFX configuration
    default: op
  wfx.bypass:
    description: Bypass all weather effects
    default: false
  wfx.elytra.bypass:
    description: Bypass elytra flight restrictions in bad weather
    default: false
  wfx.status:
    description: View plugin status
    default: op
  wfx.toggle:
    description: Toggle weather effect for yourself
    default: true
  wfx.toggle.others:
    description: Toggle weather effect for other players
    default: op
